package classessintaticas;

public interface Constants extends ScannerConstants, ParserConstants
{
    int EPSILON  = 0;
    int DOLLAR   = 1;

    int t_NUM_INTEIRO = 2;
    int t_NUM_REAL = 3;
    int t_VALOR_STRING = 4;
    int t_VALOR_CHAR = 5;
    int t_IF = 6;
    int t_ELSE = 7;
    int t_WHILE = 8;
    int t_DO = 9;
    int t_FOR = 10;
    int t_FOREACH = 11;
    int t_IN = 12;
    int t_BEGIN = 13;
    int t_END = 14;
    int t_CASE = 15;
    int t_WHEN = 16;
    int t_WRITE = 17;
    int t_READ = 18;
    int t_STRING = 19;
    int t_CHAR = 20;
    int t_DOUBLE = 21;
    int t_INT = 22;
    int t_BOOL = 23;
    int t_VOID = 24;
    int t_VETOR = 25;
    int t_SOMA = 26;
    int t_SUBTRACAO = 27;
    int t_MULTIP = 28;
    int t_DIVISAO = 29;
    int t_MOD = 30;
    int t_IGUAL = 31;
    int t_INCREMENTA = 32;
    int t_DECREMENTA = 33;
    int t_IMPR = 34;
    int t_ATRB = 35;
    int t_AND = 36;
    int t_OR_INC = 37;
    int t_OR_EXC = 38;
    int t_NOT = 39;
    int t_TRUE = 40;
    int t_FALSE = 41;
    int t_COMENT = 42;
    int t_COMENTS = 43;
    int t_PONTO = 44;
    int t_VIRGULA = 45;
    int t_PONTO_VIRG = 46;
    int t_DOIS_PONTOS = 47;
    int t_AB_COLCHETE = 48;
    int t_FC_COLCHETE = 49;
    int t_AB_PARENTESE = 50;
    int t_FC_PARENTESE = 51;
    int t_AB_CHAVE = 52;
    int t_FC_CHAVE = 53;
    int t_MAIOR = 54;
    int t_MENOR = 55;
    int t_MAIORIGUAL = 56;
    int t_MENORIGUAL = 57;
    int t_IGUALDADE = 58;
    int t_DIFERENCA = 59;
    int t_AND_L = 60;
    int t_OR_L = 61;
    int t_NOT_L = 62;
    int t_CARACTERES = 63;

}
