
package jantar;



/**
 *
 * @author João Felipe Gonçalves <joaofelipe.rode@gmail.com>
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    public JanelaPrincipal() {
        // Setup
        initComponents();
        this.setTitle("Jantar dos Filosofos - João Felipe Gonçalves");
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        botaoIniciar.addActionListener(e -> {           // Lambda expression. Necessário Java 8 para executar
            int filosofos = Integer.parseInt(campoFilosofos.getText());
            int pensando = Integer.parseInt(campoPensando.getText());
            int comendo = Integer.parseInt(campoComendo.getText());
            
            jantar = new Jantar(filosofos, pensando, comendo);
            jantar.addMensagemConsumer(msg -> System.out.println("Vindo da frame: " + msg));
        });
        
        botaoEncerrar.addActionListener(e -> {
            jantar.getMesa().setComida(false);
        });
        
        botaoSobre.addActionListener(e -> {
            new JanelaSobre();
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelSuperior = new javax.swing.JPanel();
        scrollPaneLog = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();
        painelTempo = new javax.swing.JPanel();
        campoPensando = new javax.swing.JTextField();
        labelComendo = new javax.swing.JLabel();
        labelPensando = new javax.swing.JLabel();
        campoComendo = new javax.swing.JTextField();
        painelVariaveis = new javax.swing.JPanel();
        labelFilosofos = new javax.swing.JLabel();
        campoFilosofos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();
        botaoSobre = new javax.swing.JButton();
        botaoEncerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder("Log de eventos"));

        textLog.setColumns(20);
        textLog.setRows(5);
        scrollPaneLog.setViewportView(textLog);

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneLog)
                .addContainerGap())
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneLog, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelTempo.setBorder(javax.swing.BorderFactory.createTitledBorder("Variações de tempo"));

        campoPensando.setText("20");

        labelComendo.setText("Comendo:");

        labelPensando.setText("Pensando:");

        campoComendo.setText("20");

        javax.swing.GroupLayout painelTempoLayout = new javax.swing.GroupLayout(painelTempo);
        painelTempo.setLayout(painelTempoLayout);
        painelTempoLayout.setHorizontalGroup(
            painelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTempoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelTempoLayout.createSequentialGroup()
                        .addComponent(labelPensando)
                        .addGap(8, 8, 8)
                        .addComponent(campoPensando, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelTempoLayout.createSequentialGroup()
                        .addComponent(labelComendo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoComendo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTempoLayout.setVerticalGroup(
            painelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTempoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPensando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPensando))
                .addGap(18, 18, 18)
                .addGroup(painelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComendo)
                    .addComponent(campoComendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelVariaveis.setBorder(javax.swing.BorderFactory.createTitledBorder("Variaveis"));

        labelFilosofos.setText("Filosofos:");

        campoFilosofos.setText("5");

        javax.swing.GroupLayout painelVariaveisLayout = new javax.swing.GroupLayout(painelVariaveis);
        painelVariaveis.setLayout(painelVariaveisLayout);
        painelVariaveisLayout.setHorizontalGroup(
            painelVariaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVariaveisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFilosofos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(campoFilosofos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelVariaveisLayout.setVerticalGroup(
            painelVariaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVariaveisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVariaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilosofos)
                    .addComponent(campoFilosofos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        botaoIniciar.setText("Iniciar");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        botaoSobre.setText("Sobre");

        botaoEncerrar.setText("Encerrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoEncerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoIniciar)
                            .addComponent(botaoSobre))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEncerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSobre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(painelVariaveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelVariaveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoIniciarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEncerrar;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoSobre;
    private javax.swing.JTextField campoComendo;
    private javax.swing.JTextField campoFilosofos;
    private javax.swing.JTextField campoPensando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelComendo;
    private javax.swing.JLabel labelFilosofos;
    private javax.swing.JLabel labelPensando;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel painelTempo;
    private javax.swing.JPanel painelVariaveis;
    private javax.swing.JScrollPane scrollPaneLog;
    private javax.swing.JTextArea textLog;
    // End of variables declaration//GEN-END:variables
	private Jantar jantar;
}
